spring:
  application:
    name: account-service

agenthee:
  greeting: "Hello"

---
spring:
  profiles: local
  
agenthee:
  greeting: "Hello LOCAL"

logging:
  pattern:
    console: "APP %d{yyyy-MM-dd'T'HH:mm:ss} %clr(${LOG_LEVEL_PATTERN:-%5p}) hostname='${hostName}' %m%n"
  level:
    org.springframework.web: INFO
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

---
spring:
  profiles: dev

agenthee:
  greeting: "Hello DEV"
---    
spring:
  profiles: ist

agenthee:
  greeting: "Hello IST"
---    
spring:
  profiles: uat

agenthee:
  greeting: "Hello UAT"
---    
spring:
  profiles: prod

agenthee:
  greeting: "Hello PRODUCTION"
